// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies
// @generated from protobuf file "rq/v1/resource.proto" (package "v1", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum v1.RESOURCE
 */
export enum RESOURCE {
    /**
     * @generated from protobuf enum value: METRICS = 0;
     */
    METRICS = 0,
    /**
     * @generated from protobuf enum value: TRACES = 2;
     */
    TRACES = 2,
    /**
     * @generated from protobuf enum value: LOGS = 3;
     */
    LOGS = 3,
    /**
     * @generated from protobuf enum value: SNIPPETS = 4;
     */
    SNIPPETS = 4,
    /**
     * @generated from protobuf enum value: ID = 5;
     */
    ID = 5
}
